### ISSUE TITLE
Auto-generate the CHANGELOG.md file upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/python-http-client#103]
#### Issue Summary

For every release, we currently hand craft a CHANGELOG.md update, now we would like to automate this process. Please see the existing CHANGELOG.md for formatting structure.

#### Acceptance Criteria

* A script, which when run, creates a CHANGELOG.md update based on any merged PRs since the last release.

**Comment by puzan** [comment]
Hello! I already have few solutions for changelog generation. One of them is custom python app based on gitpython, jinja2 and redmine. It creates whole change log for release branch based on version tags (regex for semver) and commit message (it should contain hashtag with issue number).

I can prepare version which will be useful for you and publish it on github in scope of hactoberfest activity. Following should be done in my app:

* Cleanup for OpenSource publish
* Add github support
* Add append changelog feature (now it generates whole changelog based on git history between tags, for example between 3.5.0 and 3.5.35)

@thinkingserious What do you think about this solution?

Also, I have question about integration. When and how do you expect to run generation. As Changelog.md is under git - automation part should have access to repository. And it is not good idea to provide any access to git for CI. So in my point of view it should be part of release procedure. Could you please describe you release procedure?

**Comment by mauricetmeyer** [comment]
@puzan from what I can tell, also seen here https://github.com/sendgrid/python-http-client/issues/92 is that it seems like that they are working on getting a CD environment up and running.

**Comment by nathanmkaya** [comment]
Hey, I'm thinking of just creating a bash script that generates the list of PR's between the current and previous release(tag) and appends the result to the top of CHANGELOG.md then pushes the changes back to Github if the changes were successfully made to the CHANGELOG.md file. It will be a bash script with the different functions to do the two actions. Pushing changes back to Github will require an access token added to travis as an encrypted variable.

**Comment by childish-sambino** [comment]
Closing as we're now using internal tool to do this.
