### ISSUE TITLE
Document new Git workflow in CHANGELOG.md

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/python-http-client#106]
#### Issue Summary

We want to update our git workflow to function more like [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). We need to update the CONTRIBUTING.md file and PULL_REQUEST_TEMPLATE to direct contributors to fork/branch off the `development` branch and to merge their PRs with the `development` branch. Once this issue is complete, we will be creating the `development` branch and making that branch the default. This is part of a larger strategy to execute releases for this SDK on a predictable cadence.

#### Acceptance Criteria

* Update CONTRIBUTING.md documentation, explaining the process of forking and branching off the `development` branch and submitting PRs agains the `development` branch.
* Update PULL_REQUEST_TEMPLATE with the same addition to the CONTRIBUTING.md documentation.

**Comment by hugovk** [comment]
Tip: once `development` branch is created, it would help to change the default branch from `master` to `development`.


> The default branch is considered the _base_ branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.

An admin can do so here: https://help.github.com/articles/setting-the-default-branch/



![image](https://user-images.githubusercontent.com/1324225/47255397-2879c380-d479-11e8-84eb-6e16e39c4da3.png)
