### ISSUE TITLE
Add our Developer Experience Engineer career opportunity to the README

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/python-http-client#114]
#### Issue Summary

The role of Developer Experience Engineer just became available and we want to announce it in the README. Here is the copy:

If you're a software engineer who is passionate about #DeveloperExperience and/or #OpenSource, [this is an incredible opportunity to join our #DX team](https://sendgrid.com/careers/role/1421152/?gh_jid=1421152) as a Developer Experience Engineer and work with @thinkingserious and @aroach! Tell your friends :)

#### Acceptance Criteria

* The above announcement is added to the Announcements section of this README

**Comment by Fantaztig** [comment]
Done in https://github.com/sendgrid/python-http-client/pull/117 :)

**Comment by lawaloy** [comment]
Hi @thinkingserious Can i take on this issue?

**Comment by childish-sambino** [comment]
Closing as the position is no longer open.
