### ISSUE TITLE
How to upload a file?

### ISSUE THREAD

**Issue by mirror222** [sendgrid/python-http-client#12]
I was trying to upload a file to an openstack (swift), it it failed:

url = 'http://192.168.1.100:8080/v1/AUTH_xxxxxxxxxxxxxxxxxxxx/container1/test.jpg'
files = {'file': open('test.jpg', 'rb')}
r = client.put(url, request_body=files, request_headers=headers)

any advice? thank you

**Comment by thinkingserious** [comment]
Hello @mirror222,

What is the error message?
