### ISSUE TITLE
Getting ModuleNotFoundError for urllib2 for starter code given in sendgrid documentation

### ISSUE THREAD

**Issue by Haider8** [sendgrid/python-http-client#126]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

* I am getting the `ModuleNotFoundError` for `urllib2` for the starter code,

#### Steps to Reproduce

1. https://app.sendgrid.com/guide/integrate/langs/python#settings/api_keys
2. Run the code given there.
3. Get the error

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* python-http-client Version: 3.2.1
* Python Version: 3.6

**Comment by thinkingserious** [comment]
Hello @Haider8,

The example code at the link you provided requires [this library](https://github.com/sendgrid/sendgrid-python). Could you please try that helper library?

I tried to reproduce this issue and I was not able to.

With best regards,

Elmer
