### ISSUE TITLE
does this support 100-continue?

### ISSUE THREAD

**Issue by AmirTadmor** [sendgrid/python-http-client#13]

**Comment by thinkingserious** [comment]
Hello @AmirTadmor,

I don't know. Could you please provide an example of what you are trying to do?

**Comment by AmirTadmor** [comment]
I am trying to upload data to a server using HTTP PUT. The problem is that the server is expecting to receive the headers first, then if it is willing to receive the data, it returns 100-continue and awaits the data from the client. Python standard http.client ignores those 100-continue replies and just stuck until the server gives up and close the connection

**Comment by thinkingserious** [comment]
@AmirTadmor,

Thanks for the elaboration. No, this support has not been added to this library. 

I'm re-labeling this issue so that it may be considered.

**Comment by akshitsarin** [comment]
I Guess it should work for now

**Comment by thinkingserious** [comment]
Hi @akshitsarin,

Did you have any success?

With Best Regards,

Elmer
