### ISSUE TITLE
pickle / celery breaks with exceptions 

### ISSUE THREAD

**Issue by syphar** [sendgrid/python-http-client#139]
### Issue Summary
We are using this library in a celery background task, using celery. (through the `sendgrid` library, and actually `django-celery-email`). 

When errors happen with the sendgrid API (like a BAD REQUEST), celery can handle this exception and normally pickle it to return it to the caller. 

Currently we are seeing a `PicklingError` where the exception type from this library can be pickled. 

As seen in [this issue](https://github.com/celery/celery/issues/3623) the problem is that in the custom exception types `super()` is not called. 

### Exception/Log
_line breaks added for readability_
```
ERROR [none] celery.worker.request: 
Task handler raised error: <MaybeEncodingError: Error sending result: 
''(1, <ExceptionInfo: BadRequestsError("<HTTPError 400: \'Bad Request\'>",)>, None)''. 
Reason: ''PicklingError("Can\'t pickle 
<class \'python_http_client.exceptions.BadRequestsError\'>: it\'s not 
the same object as python_http_client.exceptions.BadRequestsError",)''.>
```

### Technical details:
* python-http-client version: `3.2.1` 
* python version: `3.6.10`

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by wmai** [comment]
+1

**Comment by oldani** [comment]
+1

**Comment by caelean** [comment]
+1

**Comment by childish-sambino** [comment]
> +1s on the issue summary

We don't track +1s on comments.
