### ISSUE TITLE
UnboundLocalError: local variable 'exc' referenced before assignment

### ISSUE THREAD

**Issue by ThomSawyer** [sendgrid/python-http-client#144]
### Issue Summary
In the new release 3.3.0, the variable `exc` is referenced before assignement [in the client.py file](https://github.com/sendgrid/python-http-client/blob/main/python_http_client/client.py#L180). It worked fine on version 3.2.7. It looks like [L182](https://github.com/sendgrid/python-http-client/blob/main/python_http_client/client.py#L182) needs to be before [L178](https://github.com/sendgrid/python-http-client/blob/main/python_http_client/client.py#L178).

### Exception/Log
__Exception__
```
UnboundLocalError: local variable 'exc' referenced before assignment
python_http_client/client.py in _make_request at line 180
```
__Log__
```python
try:
    return opener.open(request, timeout=timeout)
except HTTPError as err:
    _logger.debug('{method} Response: {status} {body}'.format(
        method=request.get_method(),
        status=exc.status_code,
        body=exc.body))
    exc = handle_error(err)
    exc.__cause__ = None
    raise exc
```

### Technical details:
* python-http-client version: 3.3.0
* python version: 3.7

**Comment by chrislondon** [comment]
I'm getting this too

**Comment by victorct-pronto** [comment]
We are getting this too.

**Comment by childish-sambino** [comment]
Working on a fix ...

**Comment by haritn** [comment]
still getting this issue.

**Comment by mark-ix** [comment]
Still broken

**Comment by amanbedi23** [comment]
the latest pypi package still has the same issue. will this fix be updated on pypi?

**Comment by childish-sambino** [comment]
Released.
