### ISSUE TITLE
Feature Request: HTTP Client Side Compression

### ISSUE THREAD

**Issue by davemasterdave** [sendgrid/python-http-client#15]
Hi,

I have an API server (Node.js Express-based) that supports GZIP compression. Are there any plans on adding support for compression? I will be passing around large JSON objects to my API server so compression should help alot with bandwidth savings and latency reduction.

Thanks!

**Comment by mbernier** [comment]
Would you be up for having a quick chat on a google hangout? I am curious to learn more about what you're doing and where the bandwidth savings come in (questions about hosting, networking, infra, and the likes). 
If you would be cool with a chat, my email is my github user at sendgrid.com

**Comment by davemasterdave** [comment]
Hey things are super busy for me right now so i can't talk but basically I am using standard infrastructure (Digital Ocean Ubuntu droplet running a Node.js Express API) and I am using this project for a desktop sync agent I am writing in Python. I am looking GZip compression for text based assets as described in 

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer#text_compression_with_gzip 

Thanks!
