### ISSUE TITLE
Would be handy if Client was pickleable

### ISSUE THREAD

**Issue by jturmel** [sendgrid/python-http-client#18]
Using the Sendgrid Python lib (and sgbackend lib) which depends on this library (within Django), sending tasks to a background queue that first pickles the Mail being sent out, due to how Django attached the connection (backend) to each Mail object, it has an instance of the Client on it. It then pickles it to store it for the task queue and fails because pickle.dumps doesn't like the Client object, I think because __getitem__ is overrode, so from what I can tell you just need to define __setstate__ and __getstate__ on Client's implementation.

**Comment by thinkingserious** [comment]
Thanks for the suggestion @jturmel,

I have added this to our backlog. It can increase priority with additional votes or a PR.

With Best Regards,

Elmer

**Comment by jussih** [comment]
I will take a look at this
