### ISSUE TITLE
How to set the timeout parameter

### ISSUE THREAD

**Issue by PatrickHanAvaya** [sendgrid/python-http-client#20]
#### Issue Summary

Maybe I missed something, But I have no idea how to  set timeout of a http request using this library

**Comment by thinkingserious** [comment]
Hello @PatrickHanAvaya,

It looks like we need to expose that functionality [here](https://github.com/sendgrid/python-http-client/blob/master/python_http_client/client.py#L157) with [this solution](https://stackoverflow.com/a/31379309).

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

Thanks!

With Best Regards,

Elmer

**Comment by prabhakar267** [comment]
@thinkingserious I would like to take this up

**Comment by wynnw** [comment]
Hey - a +1 for this and it's associated PR. We've run into situations where this missing functionality caused us problems when trying to use the sendgrid-python library. The timeout option really needs to be available as the there's no good workaround. Right now I'm monkey patching the _make_request method which is never the happiest solution.

**Comment by thinkingserious** [comment]
Thanks for the vote @wynnw, it helps move that PR up our queue!

If you have a moment, a code review would be most appreciated and can also help this item move up the queue: https://github.com/sendgrid/python-http-client/pull/42

**Comment by thinkingserious** [comment]
This will be included in release v3.1.0 by tomorrow.

[The `Client` object now accepts a `timeout` parameter](https://github.com/sendgrid/python-http-client/blob/master/python_http_client/client.py#L62).

Thanks!
