### ISSUE TITLE
Add a Code Of Conduct

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/python-http-client#25]
Add a file to the root of this repo called CODE_OF_CONDUCT.md, with the content from the [same file in our docs repo](https://github.com/sendgrid/docs/pull/3048).

**Comment by anacidre** [comment]
Hi, I can give this one a go :)

**Comment by thinkingserious** [comment]
Thank you @anacidre!

**Comment by thinkingserious** [comment]
My apologies @anacidre, looks like this one is taken by @SvenssonWeb.
