### ISSUE TITLE
Demonstrate how to review the request body for troubleshooting

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/python-http-client#29]
When debugging, it can be useful to examine the request body before sending to the SendGrid API.

Prove an example of how to examine the request body in TROUBLESHOOTING.md. For an example, see [here](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body).

**Comment by d3vil0p3r** [comment]
@thinkingserious I'll take it 👍 
Just a clarification, do we have to put an example of how to use the function to view the request body while debugging?

**Comment by OmerAhmedKhan** [comment]
Done https://github.com/sendgrid/python-http-client/pull/30
