### ISSUE TITLE
Can't run tests without setting up a web service

### ISSUE THREAD

**Issue by iandouglas** [sendgrid/python-http-client#3]
As quick as it is to set up a simple CRUD interface in something like Flask, a user shouldn't be forced to set up entries in .env in order to run tests. Tests should have a mocked service available to run without any setup by the user.

**Comment by dtjm** [comment]
hi @iandouglas =)

**Comment by mbernier** [comment]
Hey @iandouglas!! 

Jut to confirm, are you asking for the client to default to a mocked interface if the .env is still set as the default (no entries)

Since this client doesn't call a specific API, what would the mocked interface return to the user?

**Comment by elbuo8** [comment]
@mbernier @iandouglas is right. The tests are very binded to SG usage and require dependencies that are not necessary to test the overall functionality of this agnostic client.

The mocked server would ensure that the data being passed is properly formatted/present (payload, URI, method, headers). In response you can set up dummy data that you later ensure that the library is properly parsing and assigning it to each request. So if you change the core of the library, your tests would catch if it broke the overall functionality.

cc/ @thinkingserious

**Comment by thinkingserious** [comment]
Love the feedback everyone, I'll be implementing these ideas. Thanks!

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/python-http-client/pull/5

**Comment by thinkingserious** [comment]
Fixed with: [#5](https://github.com/sendgrid/python-http-client/pull/5)
