### ISSUE TITLE
Add a PEP8 check to travis.yml

### ISSUE THREAD

**Issue by mbernier** [sendgrid/python-http-client#63]
#### Issue Summary

According to codeClimate, this repo is not conforming with PEP8 standards. Please add a PEP8 check to Travis that will cause the build to fail if the proper rules are not being met. 

#### Steps to Reproduce

1. Install the check
2. Make obvious PEP8 standards violation in one of the files
3. Make a PR
4. Let the build run
5. See a failure in the build
6. Fix the issue and make a comment (so we know)
7. Get a free Hacktoberfest shirt (so long as your first PR is in Oct)

**Comment by NdagiStanley** [comment]
- [x] Install the check

- [x] Make obvious PEP8 standards violation in one of the files

- [x] Make a PR

- [x] Let the build run

- [x] See a failure in the build

- [ ] Fix the issue and make a comment (so we know)

@mbernier The last step is being fixed by #64 , right?

**Comment by NdagiStanley** [comment]
Secondly, from the travis build we see:
![image](https://user-images.githubusercontent.com/15629602/32159481-c755c068-bd5e-11e7-8940-a8239417c108.png)

I'll update it from `pep8` to `pycodestyle`. Cool?
