### ISSUE TITLE
Make this repo conform to PEP8 standards

### ISSUE THREAD

**Issue by mbernier** [sendgrid/python-http-client#64]
#### Issue Summary

It looks like we're breaking all the rules - https://codeclimate.com/github/sendgrid/python-http-client/issues

Please update the code to fit PEP8 standards.

**Comment by jlindenger** [comment]
I spent a few minutes knocking out your PEP8 issues. There were a few more in there that I didn't see showing up on CodeClimate as well.

**Comment by Madhur96** [comment]
I want to work on this
