### ISSUE TITLE
Can't support the same query parameter twice in one URL

### ISSUE THREAD

**Issue by pkkim** [sendgrid/python-http-client#79]
#### Issue Summary

As far as I can tell, this library doesn't let you make requests to URLs which use the same query parameter key more than once, such as `http://example.com?bar=foo&bar=baz`. This is a problem because many HTTP APIs use this pattern, including SendGrid's own v3 endpoint `/subusers/reputations`. It might be good if you could pass either a dict or a list of two-tuples.

#### Steps to Reproduce

Look at python_http_client.client.Client._build_url. `query_params` is expected to be a dict, or at least something on which you can call `items`.

#### Technical details:

* python-http-client Version: discovered on 1.2.3 but looks like it's applicable to master as well (latest commit: master)
* Python Version: 3.6

**Comment by thinkingserious** [comment]
Thanks for reporting this @pkkim!

I have added this to our backlog.

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

**Comment by pkkim** [comment]
Sorry, I was mistaken about this. In fact, passing `query_params={'a': [1, 2]}` actually does produce a URL with query parameters `?a=1&a=2`. Whoops.

**Comment by thinkingserious** [comment]
No worries @pkkim. Thanks for following up!
