### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/python-http-client#92]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by georgeyk** [comment]
Hi @thinkingserious ,

The deploy to the package manager means to upload to pypi ?
Travis support pypi + https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

Do you think its enough ?

**Comment by georgeyk** [comment]
hey @thinkingserious 
Shouldn't this be closed?

**Comment by childish-sambino** [comment]
Closing as we're now using internal tool to do this.
