### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/python-http-client#97]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by ssiddhantsharma** [comment]
@thinkingserious Got it! Automating my scripts to get this done.

**Comment by arghyaiitb** [comment]
@thinkingserious I have raised a PR kindly go through it.

**Comment by thinkingserious** [comment]
Thank you @arghyaiitb,

It looks like @ssiddhantsharma may have grabbed it first, but you made the PR first.

@ssiddhantsharma, are you OK giving this one over to @arghyaiitb?

Thanks!

**Comment by ssiddhantsharma** [comment]
@arghyaiitb Take it bud!
